server:
  port: 8084  
  
spring:
  application:
    name: CloudConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Bharat5699/spring-cloud-config-server
            
